version: '3.9'
services:
  prometheus:
    container_name: tracing-nano-prometheus
    image: prom/prometheus:v2.38.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: tracing-nano-grafana
    image: grafana/grafana-oss:9.1.0
    ports:
      - "3000:3000"

  jaeger:
    container_name: tracing-nano-jaeger
    image: jaegertracing/all-in-one:1.37.0
    ports:
      - "14268:14268" # accept jaeger.thrift directly from clients (JAEGER_OVER_BINARY_HTTP)
      - "16686:16686" # jaeger ui
